name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
template: |
  ## What's Changed

  $CHANGES

  ## 📊 Summary

  **Total Changes**: $CHANGES_COUNT
  **Contributors**: $CONTRIBUTORS

  ---

  📝 **Full Changelog**: [$FULL_NAME...$PREVIOUS_NAME](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_NAME...$FULL_NAME)

  ## 🎯 What's Next?

  - [ ] Enhanced combat system
  - [ ] Multiplayer support
  - [ ] Advanced AI opponents
  - [ ] Campaign mode
  - [ ] Modding support

  ## 📥 Download

  Download the latest release from the [releases page](https://github.com/$OWNER/$REPOSITORY/releases).

  ## 🤝 Contributing

  We welcome contributions! Please see our [contributing guidelines](CONTRIBUTING.md) for details.

  ---

  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*
