# Semantic Versioning Configuration
# This file configures how semantic-release determines the next version number

# The branches on which releases should happen
branches:
  - main
  - name: 'beta'
    prerelease: true
  - name: 'alpha'
    prerelease: true

# The semantic-release plugin configuration
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'

# Commit message format for conventional commits
preset: 'conventionalcommits'

# Release rules based on commit types
releaseRules:
  - type: 'feat'
    release: 'minor'
  - type: 'fix'
    release: 'patch'
  - type: 'refactor'
    release: 'patch'
  - type: 'perf'
    release: 'patch'
  - type: 'docs'
    release: false
  - type: 'style'
    release: false
  - type: 'test'
    release: false
  - type: 'chore'
    release: false
  - type: 'ci'
    release: false
  - type: 'build'
    release: false

# Breaking changes trigger major version
breaking: true

# Pre-release configuration
prerelease: false
